### ISSUE TITLE
Mejorar la implementación de las funciones "InitRectangle" y "BoundingBox"

### ISSUE THREAD

**Issue by antcc** [antcc/practicas-mp#1]
Habría que ver si hay una forma alternativa de implementar dichas funciones, que se encuentran en
_rectangle.cpp_ y _bounding_box.cpp_, respectivamente.

**Comment by MiguelLentisco** [comment]
On it

**Comment by AlfaOmegaX** [comment]
WORTH IT

**Comment by MiguelLentisco** [comment]
Le he hecho un cambio menor, pero no se como optimizarlas, tampoco hay que comerse mucho la cabeza, ¿no?

**Comment by antcc** [comment]
Pues no, por mi lo dejamos ya así.
