### ISSUE TITLE
Ultimos detalles

### ISSUE THREAD

**Issue by MiguelLentisco** [antcc/practicas-mp#6]
1. En los matriz_bitX.cpp no pones #include "matriz_bit.h", ¿no hace falta?
2. He hecho cambios pequeños de estilo y uno grande para solo poner a 0 los bits que se quieren en la versión 4
3. Si puedes comprobar que funciona mi versión, todo completo, genial.

**Comment by antcc** [comment]
- Todo de acuerdo, pero en el SetElemento de matriz_bit3.cpp no hay que poner el carácter '\0', sino el '0'; no tienen la misma representación en la tabla ASCII. Por eso estaban así el get y el set.
- Por eso mismo también en la función Leer(), a la hora de hacer un set, hay que poner SetElemento(m,i,j,aux=='1'), porque tanto el '1' como el '0' pasan a true en un bool. 
- Lo de la función 4, lo puse que lo incializara entero a 0 porque el profesor me vio mientras lo intentaba hacer para el número exacto de bits, y me dijo que daba igual, porque a fin de cuentas el resto iban a quedarse con basura, y para eso lo llenamos todo de 0 que es más corto y eficiente.

Mañana ultimamos estos detalles, la probamos y la subimos si quieres.

PD: Lo de no poner #include "matriz_bit.h" es porque me di cuenta que en el archivo matriz_bit.cpp viene esa misma inclusión, y a fin de cuentas los matriz_bitX.cpp van a parar a ese.

**Comment by MiguelLentisco** [comment]
Entonces nada que objetar.
