### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by MiguelLentisco** [antcc/practicas-mp#7]
1. Si funciona bien el proyecto 4 con todas sus variantes, súbelo y haz merge con la línea principal.
2. Voy a crear otra rama con el boceto del proyecto 5, faltan por mirar bastantes cosas, no lo he probado siquiera.

**Comment by antcc** [comment]
1. Ok, lo he probado y va bien, lo subo y hago merge.
2. Vale, yo no lo he mirado aún, dijo el profesor que está semana no habría entrega, así que lo vamos viendo
